// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recruitment.Infrastructure.Data;

#nullable disable

namespace Recruitment.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402212248_AddApplicantDuplicateLink")]
    partial class AddApplicantDuplicateLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.Aduit.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KeyValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.DepartmentTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TitleId");

                    b.ToTable("DepartmentTitles", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.ProjectVacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VacancyId");

                    b.ToTable("ProjectVacancies", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Titles", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Vacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalaryRangeMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryRangeMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("Vacancies", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.ApplicationRejectionReason", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("RejectionReasonId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicationId", "RejectionReasonId");

                    b.HasIndex("RejectionReasonId");

                    b.ToTable("ApplicationRejectionReason");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("InterViewNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterviewCategory")
                        .HasColumnType("int");

                    b.Property<int>("InterviewResult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("InterviewStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("InterviewType")
                        .HasColumnType("int");

                    b.Property<int>("InterviewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("InterviewerId");

                    b.ToTable("Interviews", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.InterviewRejectionReason", b =>
                {
                    b.Property<int>("InterviewId")
                        .HasColumnType("int");

                    b.Property<int>("RejectionReasonId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("InterviewId", "RejectionReasonId");

                    b.HasIndex("RejectionReasonId");

                    b.ToTable("InterviewRejectionReason");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.Interviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Interviewers", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.RejectionReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReasonType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RejectionReasons", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.Recruitment_Proccess.ApplicantApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualFirstDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedFirstDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("VacancyId");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.Reports.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredProcedure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.Reports.ReportParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportParameters");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CVFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentEmployer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CurrentJob")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("CurrentSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EducationDegree")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("ExpectedSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExtraCertificate")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<short?>("GraduationYear")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<int?>("MasterApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("MilitaryStatus")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NoticePeriod")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OfferStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetPosition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("MasterApplicantId");

                    b.ToTable("Applicants", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 9,
                            Action = "Create",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to add applicants to the system",
                            IsDeleted = false,
                            PermissionName = "Add new Applicant",
                            Resource = "Applicant"
                        },
                        new
                        {
                            Id = 10,
                            Action = "Create",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to add vacancy to the system",
                            IsDeleted = false,
                            PermissionName = "Add new Vacancy",
                            Resource = "Vacancy"
                        },
                        new
                        {
                            Id = 11,
                            Action = "Edit",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to Edit on vacancy data",
                            IsDeleted = false,
                            PermissionName = "Make changes to existence vacancy",
                            Resource = "Vacancy"
                        },
                        new
                        {
                            Id = 12,
                            Action = "Assign",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to assign a job applicant in order to create application for him/her",
                            IsDeleted = false,
                            PermissionName = "Assign applicants to open vacancies",
                            Resource = "Vacancy"
                        },
                        new
                        {
                            Id = 13,
                            Action = "ViewSubmission",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to see who applied for this Vacancy",
                            IsDeleted = false,
                            PermissionName = "View submission for specific Vacancy",
                            Resource = "Vacancy"
                        },
                        new
                        {
                            Id = 14,
                            Action = "Delete",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to delete vacancies",
                            IsDeleted = false,
                            PermissionName = "Delete specific Vacancy",
                            Resource = "Vacancy"
                        },
                        new
                        {
                            Id = 15,
                            Action = "Assign",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to assign a job applicant in order to create application for him/her",
                            IsDeleted = false,
                            PermissionName = "Assign vacancies to applicants",
                            Resource = "Applicant"
                        },
                        new
                        {
                            Id = 16,
                            Action = "ViewHistory",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to view specific applicant's history",
                            IsDeleted = false,
                            PermissionName = "Show applicant's history",
                            Resource = "Applicant"
                        },
                        new
                        {
                            Id = 17,
                            Action = "Edit",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing user to edit applicant's data",
                            IsDeleted = false,
                            PermissionName = "Make changes to existence Applicant's information",
                            Resource = "Applicant"
                        },
                        new
                        {
                            Id = 18,
                            Action = "Delete",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to delete applicants",
                            IsDeleted = false,
                            PermissionName = "Delete specific applicant",
                            Resource = "Applicant"
                        },
                        new
                        {
                            Id = 19,
                            Action = "ReviewApplication",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to make changes to application's status",
                            IsDeleted = false,
                            PermissionName = "Take action about specific application",
                            Resource = "Application"
                        },
                        new
                        {
                            Id = 20,
                            Action = "RegisterFinalResult",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing user to submit the final result for the interviews",
                            IsDeleted = false,
                            PermissionName = "Register interview's final result",
                            Resource = "Interview"
                        },
                        new
                        {
                            Id = 21,
                            Action = "Edit",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to modify interview details",
                            IsDeleted = false,
                            PermissionName = "Make changes to existence interview",
                            Resource = "Interview"
                        },
                        new
                        {
                            Id = 22,
                            Action = "Create",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to add project to the system",
                            IsDeleted = false,
                            PermissionName = "Add new project",
                            Resource = "Project"
                        },
                        new
                        {
                            Id = 23,
                            Action = "Edit",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to change project's name, status, or location",
                            IsDeleted = false,
                            PermissionName = "Make changes to existence Project",
                            Resource = "Project"
                        },
                        new
                        {
                            Id = 24,
                            Action = "Create",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to add new job title to the system",
                            IsDeleted = false,
                            PermissionName = "Add new Job title",
                            Resource = "Title"
                        },
                        new
                        {
                            Id = 25,
                            Action = "Edit",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to edit title name or department",
                            IsDeleted = false,
                            PermissionName = "Make changes to existence Job title",
                            Resource = "Title"
                        },
                        new
                        {
                            Id = 26,
                            Action = "Create",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to add new location to the system",
                            IsDeleted = false,
                            PermissionName = "Add new Location",
                            Resource = "Location"
                        },
                        new
                        {
                            Id = 27,
                            Action = "Edit",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to edit location data",
                            IsDeleted = false,
                            PermissionName = "Make changes to existence location",
                            Resource = "Location"
                        },
                        new
                        {
                            Id = 28,
                            Action = "Create",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to add new interviewer",
                            IsDeleted = false,
                            PermissionName = "Add new Interviewer",
                            Resource = "Interviewer"
                        },
                        new
                        {
                            Id = 29,
                            Action = "Edit",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to edit interviewer data",
                            IsDeleted = false,
                            PermissionName = "Make changes to existence interviewer",
                            Resource = "Interviewer"
                        },
                        new
                        {
                            Id = 30,
                            Action = "Delete",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to delete interviewer",
                            IsDeleted = false,
                            PermissionName = "Delete specific interviewer",
                            Resource = "Interviewer"
                        },
                        new
                        {
                            Id = 31,
                            Action = "Create",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to add rejection reasons",
                            IsDeleted = false,
                            PermissionName = "Add rejection reasons to the system",
                            Resource = "RejectionReason"
                        },
                        new
                        {
                            Id = 32,
                            Action = "Edit",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to edit rejection reason",
                            IsDeleted = false,
                            PermissionName = "Make changes to existence rejection reason",
                            Resource = "RejectionReason"
                        },
                        new
                        {
                            Id = 33,
                            Action = "Delete",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to delete rejection reasons",
                            IsDeleted = false,
                            PermissionName = "Delete specific rejection reason",
                            Resource = "RejectionReason"
                        },
                        new
                        {
                            Id = 34,
                            Action = "Create",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to add department",
                            IsDeleted = false,
                            PermissionName = "Add new departments",
                            Resource = "Department"
                        },
                        new
                        {
                            Id = 35,
                            Action = "View",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to see departments",
                            IsDeleted = false,
                            PermissionName = "View Department",
                            Resource = "Department"
                        },
                        new
                        {
                            Id = 36,
                            Action = "Edit",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing user to edit department name",
                            IsDeleted = false,
                            PermissionName = "Make changes to existence department's name",
                            Resource = "Department"
                        },
                        new
                        {
                            Id = 37,
                            Action = "Delete",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing user to delete department",
                            IsDeleted = false,
                            PermissionName = "Delete specific Department",
                            Resource = "Department"
                        },
                        new
                        {
                            Id = 38,
                            Action = "View",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing user to view location list",
                            IsDeleted = false,
                            PermissionName = "View Locations",
                            Resource = "Location"
                        },
                        new
                        {
                            Id = 39,
                            Action = "View",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to view job title list",
                            IsDeleted = false,
                            PermissionName = "View titles",
                            Resource = "Title"
                        },
                        new
                        {
                            Id = 40,
                            Action = "View",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to view projects list",
                            IsDeleted = false,
                            PermissionName = "View Projects",
                            Resource = "Project"
                        },
                        new
                        {
                            Id = 41,
                            Action = "View",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to view rejection reasons list",
                            IsDeleted = false,
                            PermissionName = "View Rejection Reasons",
                            Resource = "RejectionReason"
                        },
                        new
                        {
                            Id = 42,
                            Action = "View",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to view interviewer lists",
                            IsDeleted = false,
                            PermissionName = "View interviewers list",
                            Resource = "Interviewer"
                        },
                        new
                        {
                            Id = 43,
                            Action = "View",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to manage countries",
                            IsDeleted = false,
                            PermissionName = "View and manage Countries module",
                            Resource = "Country"
                        },
                        new
                        {
                            Id = 44,
                            Action = "View",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to manage currency",
                            IsDeleted = false,
                            PermissionName = "View and manage Currency module",
                            Resource = "Currency"
                        },
                        new
                        {
                            Id = 45,
                            Action = "Create",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to schedule an interview",
                            IsDeleted = false,
                            PermissionName = "Add Interview for specific application in the system",
                            Resource = "Interview"
                        },
                        new
                        {
                            Id = 46,
                            Action = "Delete",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to delete location",
                            IsDeleted = false,
                            PermissionName = "Delete Location",
                            Resource = "Location"
                        },
                        new
                        {
                            Id = 47,
                            Action = "Delete",
                            CreatedBy = "admin@rsc.com.eg",
                            CreatedOn = new DateTime(2026, 3, 24, 11, 12, 1, 0, DateTimeKind.Unspecified),
                            Description = "Allowing the user to delete title",
                            IsDeleted = false,
                            PermissionName = "Delete specific Title",
                            Resource = "Title"
                        });
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrantedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserProject", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProjectId")
                        .IsUnique();

                    b.ToTable("UserProjects", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.UserManagement.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.UserManagement.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.UserManagement.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.UserManagement.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.UserManagement.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.UserManagement.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.DepartmentTitle", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Department", "Department")
                        .WithMany("DepartmentTitles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Title", "Title")
                        .WithMany("DepartmentTitles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Location", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Country", "Country")
                        .WithMany("Locations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Project", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Location", "Location")
                        .WithMany("Projects")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.ProjectVacancy", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Project", "Project")
                        .WithMany("ProjectVacancies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Vacancy", "Vacancy")
                        .WithMany("ProjectVacancies")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Vacancy", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Title", "Title")
                        .WithMany("Vacancies")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.ApplicationRejectionReason", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.Recruitment_Proccess.ApplicantApplication", "Application")
                        .WithMany("RejectionReasons")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.RecruitmentProccess.RejectionReason", "RejectionReason")
                        .WithMany("Applications")
                        .HasForeignKey("RejectionReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("RejectionReason");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.Interview", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.Recruitment_Proccess.ApplicantApplication", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.RecruitmentProccess.Interviewer", "Interviewer")
                        .WithMany("Interviews")
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.InterviewRejectionReason", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.RecruitmentProccess.Interview", "Interview")
                        .WithMany("RejectionReasons")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.RecruitmentProccess.RejectionReason", "RejectionReason")
                        .WithMany("Interviews")
                        .HasForeignKey("RejectionReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("RejectionReason");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.Interviewer", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Department", "Department")
                        .WithMany("Interviewers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.Recruitment_Proccess.ApplicantApplication", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.UserManagement.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.UserManagement.User", "Reviewer")
                        .WithMany("ReviewedApplications")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Vacancy", "Vacancy")
                        .WithMany("Applications")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Reviewer");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.Reports.ReportParameter", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.Reports.Report", "Report")
                        .WithMany("Parameters")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.Applicant", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.UserManagement.Applicant", "MasterApplicant")
                        .WithMany("Duplicates")
                        .HasForeignKey("MasterApplicantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("Currency");

                    b.Navigation("MasterApplicant");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.RolePermission", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.UserManagement.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.UserManagement.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.Domain.Entities.UserManagement.User", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("UserId");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.User", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserProject", b =>
                {
                    b.HasOne("Recruitment.Domain.Entities.CoreBusiness.Project", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Recruitment.Domain.Entities.UserManagement.User", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Country", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Department", b =>
                {
                    b.Navigation("DepartmentTitles");

                    b.Navigation("Interviewers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Location", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Project", b =>
                {
                    b.Navigation("ProjectVacancies");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Title", b =>
                {
                    b.Navigation("DepartmentTitles");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.CoreBusiness.Vacancy", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ProjectVacancies");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.Interview", b =>
                {
                    b.Navigation("RejectionReasons");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.Interviewer", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.RecruitmentProccess.RejectionReason", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.Recruitment_Proccess.ApplicantApplication", b =>
                {
                    b.Navigation("Interviews");

                    b.Navigation("RejectionReasons");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.Reports.Report", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.Applicant", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Duplicates");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Recruitment.Domain.Entities.UserManagement.User", b =>
                {
                    b.Navigation("ReviewedApplications");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
